# Generated by Django 3.1.7 on 2021-03-14 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contentapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=60)),
                ('pdf', models.BooleanField()),
                ('categories', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Arts', 'Arts')], max_length=35, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
